In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [3]:
df = pd.read_csv('amocrm_sample_export.csv')

In [5]:
#Вывод таблицы во всю ширину
pd.set_option('display.max_columns', None)
df.head(5)

,ID,Этап сделки,Бюджет,Дата создания сделки,Дата закрытия,DELIVERY_PRICE,Стоимость доставки,PRODUCTS,PRICE,SUBTOTAL,Выручка от клиента,Направление (вид сертификата),Номер сертификата,КОРНЕВАЯ СДЕЛКА,Номер 2-го сертификата,Сертификат на фотографа,Сертификат на тренера,Статус погашения,Дата оплаты подрядчику
0,26165303,Успешно реализовано,5500,30.11.2023 17:43:20,30.11.2023 18:00:00,0.0,NaN,катание на картинге (Варианты: 40 минут катани...,5500.0,5500.0,5500,Картинг,VKA4_4314611,NaN,NaN,NaN,NaN,NaN,NaN
1,26163311,Успешно реализовано,8000,30.11.2023 14:58:27,01.12.2023 15:09:00,NaN,NaN,Мотокросс и Эндуро (Варианты: Персональная тре...,8000.0,8000.0,8000,Мото Мотокросс,MT 273176,NaN,NaN,NaN,NaN,NaN,NaN
2,26162989,Успешно реализовано,5450,30.11.2023 14:33:51,01.12.2023 15:20:00,450.0,NaN,Стрельба из боевого оружия (Варианты: Курс «на...,5450.0,5000.0,5450,Тир. Стрельба из боевого оружия,GU2 21041,NaN,NaN,NaN,NaN,NaN,NaN
3,26160427,Успешно реализовано,34567,30.11.2023 11:37:23,02.12.2023 16:01:00,NaN,NaN,"Универсальный 23456 (Варианты: 34 567 руб., Бу...",34567.0,34567.0,34567,Универс. 23.456 и 34.567,WTF3 269703,NaN,NaN,NaN,NaN,NaN,NaN
4,26158865,Успешно реализовано,9000,30.11.2023 09:39:04,30.11.2023 09:47:00,NaN,NaN,Аэротруба (Варианты: 10 минут полёта (для 1-2 ...,9000.0,9000.0,9000,Аэротруба,VAT10 4353286,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Вывод таблицы во всю ширину
pd.set_option('display.max_columns', None)
df.head(5)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2622 entries, 0 to 2621
Data columns (total 19 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   ID                             2622 non-null   int64
 1   Этап сделки                    2622 non-null   object
 2   Бюджет                         2622 non-null   int64
 3   Дата создания сделки           2622 non-null   object
 4   Дата закрытия                  2622 non-null   object
 5   DELIVERY_PRICE                 1647 non-null   float64
 6   Стоимость доставки             9 non-null      float64
 7   PRODUCTS                       2452 non-null   object
 8   PRICE                          2452 non-null   float64
 9   SUBTOTAL                       2452 non-null   float64
 10  Выручка от клиента             2498 non-null   object
 11  Направление (вид сертификата)  2622 non-null   object
 12  Номер сертификата              2622 non-null   object
 13  КОРНЕВАЯ СДЕЛКА                135 non-null    object
 14  Номер 2-го сертификата         82 non-null     object
 15  Сертификат на фотографа        16 non-null     object
 16  Сертификат на тренера          97 non-null     object
 17  Статус погашения               1048 non-null   object
 18  Дата оплаты подрядчику         1052 non-null   object
dtypes: float64(4), int64(2), object(13)
memory usage: 389.3+ KB